name: PR Tracker Cron

on:
  schedule:
    - cron: "30 16 * * *"
  workflow_dispatch: # allows manual run

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call PR Tracker API
        run: |
          curl --max-time 30 -X POST https://p1-pr-tracker.onrender.com/send-to-slack || echo "Request failed"
